baseURL = 'https://amazing-volhard-946549.netlify.app/'
languageCode = 'zh-cn'
title = 'Go Beyond Oneself'
theme = 'hugo-coder'
pygmentsStyle = "bw"
[params] # theme parameters
    author = "Lijun Liu" # author's name
    info = "Full Stack Developer" # author's job title or info
    description = "John Doe's personal website" # site description
    keywords = "blog,developer,personal" # site keywords

    custom_css = ["/css/main.css"]
    
# Social links
[[params.social]]
    name = "WeChat"
    weight = 3
    url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/liulijun-dev"
[[params.social]]
    name = "CSDN"
    weight = 2
    url = "https://blog.csdn.net/l460133921"
[[params.social]]
    name = "çŸ¥ä¹"
    weight = 3
    url = "https://www.linkedin.com/in/johndoe/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]
            [[languages.en.menu.main]]
                name = "Learning"
                weight = 1
                url  = "/learning/"
            [[languages.en.menu.main]]
                name = "Technology"
                weight = 2
                url  = "/topic/"
            [[languages.en.menu.main]]
                name = "Team Manager"
                weight = 3
                url  = "/team/"
            [[languages.en.menu.main]]
                name = "Project"
                weight = 4
                url  = "/project/"
            [[languages.en.menu.main]]
                name = "About"
                weight = 5
                url = "/about/"

    [languages.zh-cn]
        languagename = "Chinese"
        title = "è¶…è¶Šè‡ªæˆ‘"

        [languages.zh-cn.params]
            author = "Lijun Liu"
            info1 = "ğŸ“š"
            info1Tooltip = "ç»ˆèº«å­¦ä¹ /è®¤çŸ¥æ æ†"
            info2 = "ğŸ‘¨â€ğŸ’»"
            info2Tooltip = "å…¨æ ˆæŠ€æœ¯/æ—¶é—´æ æ†"
            info3 = "ğŸ’´"
            info3Tooltip = "æŠ•èµ„ç†è´¢/è´¢åŠ¡æ æ†"
            description = "é€šè¿‡å­¦ä¹ ï¼ˆGTDã€æ—¶é—´ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€å†™ä½œã€è´¢åŠ¡ç®¡ç†ï¼‰ã€æŠ€æœ¯åˆ›é€ ï¼ˆå‰ç«¯ã€åç«¯ã€ç§»åŠ¨ç«¯ã€DevOpsï¼‰ã€æŠ•èµ„ï¼ˆæŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ï¼‰ã€ç½‘èµšé¡¹ç›®ï¼ˆSEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ï¼‰æ¥å»ºç«‹è¢«åŠ¨æ”¶å…¥"
            keywords = "è‡ªæˆ‘æå‡ã€æ—¶é—´ç®¡ç†ã€GTDã€å†™ä½œã€æ‘„å½±ã€ç¬”è®°ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€è´¢åŠ¡ç®¡ç†ã€å…¨æ ˆå¼€å‘ã€æŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ã€SEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ã€è¢«åŠ¨æ”¶å…¥ã€ç½‘èµš"
            # footercontent = "self/dev/money"

        [languages.zh-cn.menu]
            [[languages.zh-cn.menu.main]]
                name = "å­¦ä¹ "
                weight = 1
                url  = "/learning/"
            [[languages.zh-cn.menu.main]]
                name = "æŠ€æœ¯ä¸“é¢˜"
                weight = 2
                url  = "/topic/"
            [[languages.zh-cn.menu.main]]
                name = "å›¢é˜Ÿç®¡ç†"
                weight = 3
                url  = "/team/"
            [[languages.zh-cn.menu.main]]
                name = "ä¸ªäººé¡¹ç›®"
                weight = 4
                url  = "/project/"
            [[languages.zh-cn.menu.main]]
                name = "å…³äº"
                weight = 5
                url = "/about/"

